name: example
description: FlexibleGrid example

version: 1.0.0

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter

  flexible_grid:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

publish_to: none